---
daemonset:
  count: 1
  name: statusbay-daemonset
  image:
    repository: nginx
    tag: latest
    pullPolicy: IfNotPresent

  # resources:
  #   requests:
  #     memory: 256Mi
  #     cpu: 100m

  livenessProbe:
    httpGet:
      path: /
      port: 80
  readinessProbe:
    httpGet:
      path: /
      port: 80
    
  annotations:
    statusbay.io/progress-deadline-seconds: "30"
    statusbay.io/application-name: "statusbay-application"
    statusbay.io/report-slack-channels: "#foo-channel"
    statusbay.io/report-deploy-by: foo@similarweb.com
    statusbay.io/alerts-pingdom: nginx
    statusbay.io/metrics-datadog-2xx: query for 2xx
    statusbay.io/metrics-datadog-errors-5xx: query for 5xx
    # statusbay.io/alerts-statuscake: nginx
    # statusbay.io/metrics-prometheus-errors-title-5xx: query for 4xx
    
deployment:
  count: 1
  replicas: 3
  progressDeadlineSeconds: 300
  name: statusbay-deployment
  image:
    repository: nginx
    tag: latest
    pullPolicy: IfNotPresent

  # resources:
  #   requests:
  #     memory: 256Mi
  #     cpu: 100m

  livenessProbe:
    httpGet:
      path: /
      port: 80
  readinessProbe:
    httpGet:
      path: /
      port: 80
    
  annotations:
    statusbay.io/progress-deadline-seconds: "30"
    statusbay.io/application-name: "statusbay-application"
    statusbay.io/report-slack-channels: "#foo-channel"
    statusbay.io/report-deploy-by: foo@similarweb.com
    statusbay.io/alerts-pingdom: nginx
    statusbay.io/metrics-datadog-2xx: query for 2xx
    statusbay.io/metrics-datadog-errors-5xx: query for 5xx
    # statusbay.io/alerts-statuscake: nginx
    # statusbay.io/metrics-prometheus-errors-title-5xx: query for 4xx
